name: kactor_client
description: A Dart/Flutter client for the kactor WebSocket server
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0 